import matplotlib.pyplot as plt

def plotcurve(modelname, day, obj, postion, train_l, test_l, train_acc, test_acc, train_f1, test_f1):
    plt.figure(1)
    plt.title('Day' + str(day) + '_s' + str(obj) + '_' + str(postion) + '_loss')
    plt.plot(train_l, label='trainloss')
    plt.plot(test_l, label='testloss')
    plt.legend(loc="lower right", fontsize=6)
    plt.savefig('./curve/' + 'TCN' + '/Day' + str(day) + '_s' + str(obj) + '_' + str(postion) + '_loss')
    # plt.show()
    plt.figure(2)
    plt.title('Day' + str(day) + '_s' + str(obj) + '_' + str(postion) + '_acc')
    plt.plot(train_acc, label='trainacc')
    plt.plot(test_acc, label='testacc')
    plt.legend(loc="lower right", fontsize=6)
    plt.savefig('./curve/' + modelname + '/Day' + str(day) + '_s' + str(obj) + '_' + str(postion) + '_acc')
    # plt.show()
    # plt.figure(3)
    # plt.title('s' + str(obj) + '_' + str(postion) + '_f1')
    # plt.plot(train_f1, label='trainf1')
    # plt.plot(test_f1, label='testf1')
    # plt.legend( loc="lower right", fontsize=6)
    # plt.savefig('./curve/' + modelname + '/s' + str(obj) + '_' + str(postion) + '_f1')
    # plt.show()
